"""databasecreation

Revision ID: b535c851fc52
Revises: 
Create Date: 2024-04-14 15:31:16.607239

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b535c851fc52"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickers",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("daily_volume", sa.BigInteger(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "correlations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("master_symbol", sa.String(), nullable=True),
        sa.Column("slave_symbol", sa.String(), nullable=True),
        sa.Column("corellation_coef", sa.Float(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["master_symbol"],
            ["tickers.symbol"],
        ),
        sa.ForeignKeyConstraint(
            ["slave_symbol"],
            ["tickers.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "klines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("open_time", sa.DateTime(), nullable=False),
        sa.Column("qouto_asset_vol", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["tickers.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument", sa.String(), nullable=True),
        sa.Column("last_short_term_corellation", sa.Integer(), nullable=True),
        sa.Column("current_trade_volume", sa.Float(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument"],
            ["tickers.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("positions")
    op.drop_table("klines")
    op.drop_table("correlations")
    op.drop_table("tickers")
    # ### end Alembic commands ###
