"""databaseupdate

Revision ID: e3b3a84bcf85
Revises: e4f3ffa10a22
Create Date: 2024-04-03 22:19:54.356864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b3a84bcf85'
down_revision = 'e4f3ffa10a22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('futures', sa.Column('daily_volume', sa.BigInteger(), nullable=True))
    op.drop_column('futures', 'dayly_volume')
    op.add_column('positions', sa.Column('instrument', sa.String(), nullable=True))
    op.add_column('positions', sa.Column('last_short_term_corellations', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'positions', 'futures', ['instrument'], ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_column('positions', 'last_short_term_corellations')
    op.drop_column('positions', 'instrument')
    op.add_column('futures', sa.Column('dayly_volume', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('futures', 'daily_volume')
    # ### end Alembic commands ###
