"""databasecreation

Revision ID: e4f3ffa10a22
Revises: 
Create Date: 2024-04-03 21:46:06.070854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f3ffa10a22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('dayly_volume', sa.Integer(), nullable=True),
    sa.Column('history_correlation', sa.Float(), nullable=True),
    sa.Column('current_correlation', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_additions_number', sa.Integer(), nullable=False),
    sa.Column('current_trade_volume', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_symbol', sa.String(), nullable=True),
    sa.Column('slave_symbol', sa.String(), nullable=True),
    sa.Column('corellation_coef', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_symbol'], ['futures.symbol'], ),
    sa.ForeignKeyConstraint(['slave_symbol'], ['futures.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('klines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('qouto_asset_vol', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['futures.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('klines')
    op.drop_table('correlations')
    op.drop_table('positions')
    op.drop_table('futures')
    # ### end Alembic commands ###
