"""databaseupdate

Revision ID: f0933f7e1dfb
Revises: 9f65775a6155
Create Date: 2024-03-30 01:34:10.848851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f0933f7e1dfb"
down_revision = "9f65775a6155"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("klines", sa.Column("close_time", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("klines", "close_time")
    # ### end Alembic commands ###
